import type { CurrentUser } from '../auth/types'
import { escapeHtml } from '../../shared/ui/html'
import type { StaffUser } from './types'

export type SupportSection = 'admins' | 'patients' | 'professionals'

function shell(user: CurrentUser, content: string, active: SupportSection): string {
  const name = `${user.persona.nombres} ${user.persona.apellidos}`.trim() || user.username
  const links = [['admins', 'Manejadores', '#/cuentas'], ['patients', 'Pacientes', '#/pacientes'], ['professionals', 'Médicos', '#/medicos']] as const
  return `<div class="portal-shell"><aside class="sidebar"><a class="portal-brand portal-brand--sidebar" href="#/afiliaciones"><img src="/favicon.svg" alt="" /><span>Lumora</span></a><nav class="sidebar__nav" aria-label="Navegación del portal"><a class="sidebar__link" href="#/afiliaciones"><span aria-hidden="true">▪</span>Afiliaciones</a>${links.map(([key, label, href]) => `<a class="sidebar__link ${active === key ? 'is-active' : ''}" href="${href}"><span aria-hidden="true">◇</span>${label}</a>`).join('')}</nav><div class="sidebar__foot"><span>Portal interno</span><small>Administración y soporte</small></div></aside><div class="portal-main"><header class="topbar"><div><strong>${escapeHtml(name)}</strong><span>${escapeHtml(user.email)}</span></div><button class="button button--outline button--small" type="button" data-action="logout">Cerrar sesión</button></header>${content}</div></div>`
}

function supportPanel(title: string, role: string, users: StaffUser[]): string {
  const matching = users.filter((user) => user.roles.some((item) => item.nombre === role))
  const rows = matching.map((item) => `<tr data-support-row data-search="${escapeHtml(`${item.persona.nombres} ${item.persona.apellidos} ${item.username} ${item.email}`.toLowerCase())}"><td><strong>${escapeHtml(`${item.persona.nombres} ${item.persona.apellidos}`)}</strong><span class="table-secondary">${escapeHtml(item.username)}</span></td><td>${escapeHtml(item.email)}</td><td><span class="badge ${item.activo ? 'badge--active' : 'badge--suspended'}">${item.activo ? 'Activa' : 'Inactiva'}</span><span class="table-secondary">${item.email_verificado ? 'Correo verificado' : 'Correo pendiente'}</span></td><td class="table-action"><button class="table-link" type="button" data-resend-password="${item.id}">Reenviar contraseña</button></td></tr>`).join('')
  return `<section class="panel"><div class="panel__header"><div><h2>${title}</h2><p>${matching.length} cuentas encontradas</p></div><span class="panel-count">${matching.length}</span></div>${matching.length ? `<div class="table-wrap"><table><thead><tr><th>Persona</th><th>Correo</th><th>Estado</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>` : '<div class="empty-state"><strong>No hay cuentas en este panel.</strong><span>Las cuentas aparecen cuando tienen el rol correspondiente.</span></div>'}</section>`
}

export function UsersView(user: CurrentUser, users: StaffUser[], section: SupportSection): string {
  const config = section === 'patients' ? { title: 'Pacientes', role: 'Paciente', eyebrow: 'Soporte de pacientes', description: 'Consulta y ayuda a pacientes registrados en Lumora.' } : section === 'professionals' ? { title: 'Médicos', role: 'Profesional de Salud', eyebrow: 'Soporte médico', description: 'Busca médicos y gestiona sus correos de acceso.' } : { title: 'Manejadores', role: 'Administrador', eyebrow: 'Cuentas Lumora', description: 'Administra las cuentas internas de los manejadores de Lumora.' }
  return shell(user, `<main class="portal-content"><div class="page-heading"><div><span class="eyebrow">${config.eyebrow}</span><h1>${config.title}</h1><p>${config.description}</p></div>${section === 'admins' ? '<button class="button" type="button" data-action="open-create-user">Nueva cuenta</button>' : ''}</div><div class="panel"><label class="field"><span>Buscar ${config.title.toLowerCase()}</span><input type="search" placeholder="Nombre, usuario o correo" data-support-search /></label></div>${supportPanel(config.title, config.role, users)}${section === 'admins' ? `<dialog class="portal-dialog" data-create-user-dialog><form class="dialog-card" data-create-user-form><div class="dialog-card__header"><div><span class="eyebrow">Nueva cuenta</span><h2>Crear cuenta de manejador</h2><p>Define una contraseña inicial; luego puedes reenviar el correo de cambio de contraseña.</p></div><button class="icon-button" type="button" aria-label="Cerrar" data-action="close-dialog">×</button></div><div class="form-grid form-grid--2"><label class="field"><span>Nombres</span><input name="first_names" maxlength="100" required /></label><label class="field"><span>Apellidos</span><input name="last_names" maxlength="100" required /></label><label class="field"><span>Usuario</span><input name="username" autocomplete="username" maxlength="50" required /></label><label class="field"><span>Correo</span><input name="email" type="email" autocomplete="email" maxlength="255" required /></label><label class="field form-grid__wide"><span>Contraseña inicial</span><input name="password" type="password" autocomplete="new-password" minlength="8" maxlength="128" required /></label></div><div class="dialog-card__actions"><button class="button button--outline" type="button" data-action="close-dialog">Cancelar</button><button class="button" type="submit">Crear cuenta</button></div></form></dialog>` : ''}</main>` , section)
}