import type {
  ClinicalTimelineItem,
  PatientClinicalSummary,
} from '../types/medical-record.types';

export const previewMedicalRecordSummaries: Record<number, PatientClinicalSummary> = {
  101: {
    paciente_id: 101,
    paciente: {
      id: 8101,
      nombres: 'Ana',
      apellidos: 'Morales',
      fecha_nacimiento: '1988-06-14',
      sexo_id: 2,
    },
    expediente: {
      id: 7001,
      paciente_id: 101,
      estado_expediente_id: 1,
      numero_expediente: 'LM-2026-0101',
      notas: 'Seguimiento metabólico y cardiovascular.',
      activo: true,
    },
    antecedentes: [
      {
        id: 3001,
        expediente_id: 7001,
        tipo_antecedente_id: 1,
        descripcion: 'Antecedente familiar de hipertensión arterial.',
        fecha: '2025-08-20',
        activo: true,
      },
    ],
    alergias: [
      {
        id: 3101,
        paciente_id: 101,
        nombre: 'Penicilina',
        nivel_severidad_id: 3,
        estado_condicion_id: 1,
        observaciones: 'Erupción cutánea documentada.',
        activo: true,
      },
    ],
    discapacidades: [],
    condiciones: [
      {
        id: 3201,
        expediente_id: 7001,
        paciente_id: 101,
        diagnostico_id: 3301,
        estado_condicion_id: 1,
        nombre: 'Hipertensión arterial',
        descripcion: 'En seguimiento clínico.',
        fecha_inicio: '2024-04-02',
        fecha_fin: null,
        activo: true,
      },
    ],
    consultas: [
      {
        consulta: {
          id: 3401,
          expediente_id: 7001,
          paciente_id: 101,
          profesional_id: 101,
          motivo_consulta_id: 1,
          fecha_consulta: '2026-08-24T15:30:00.000Z',
          motivo: 'Control de presión arterial',
          sintomas: null,
          evaluacion: 'Paciente estable durante el control.',
          indicaciones: 'Continuar seguimiento.',
          observaciones: null,
          activo: true,
        },
        signos_vitales: [
          {
            id: 3501,
            consulta_id: 3401,
            temperatura_c: 36.7,
            frecuencia_cardiaca: 74,
            frecuencia_respiratoria: 16,
            presion_sistolica: 138,
            presion_diastolica: 86,
            saturacion_oxigeno: 98,
            peso_kg: 68,
            talla_cm: 165,
            glucosa_mg_dl: 108,
            registrado_at: '2026-08-24T15:35:00.000Z',
          },
        ],
        notas: [
          {
            id: 3601,
            consulta_id: 3401,
            autor_id: 9001,
            contenido: 'Sin signos de alarma durante la consulta.',
            created_at: '2026-08-24T15:40:00.000Z',
            updated_at: '2026-08-24T15:40:00.000Z',
            activo: true,
          },
        ],
        diagnosticos: [
          {
            id: 3301,
            consulta_id: 3401,
            expediente_id: 7001,
            profesional_id: 101,
            tipo_diagnostico_id: 1,
            descripcion: 'Hipertensión arterial primaria',
            es_principal: true,
            fecha_diagnostico: '2026-08-24',
            activo: true,
          },
        ],
      },
    ],
    recetas: [
      {
        id: 'rx-preview-101',
        profesional_id: 101,
        consulta_id: 3401,
        estado_id: 1,
        titulo: 'Control antihipertensivo',
        fecha_emision: '2026-08-24T15:45:00.000Z',
        vigencia_hasta: '2026-09-24T15:45:00.000Z',
      },
    ],
    mediciones: [
      {
        id: 'measure-preview-101',
        indicador_id: 'indicator-pressure-preview',
        indicador_nombre: 'Presión sistólica',
        valor: 138,
        unidad_medida_id: 9,
        unidad_medida: 'mmHg',
        origen_registro_id: 3,
        fecha_medicion: '2026-08-24T15:35:00.000Z',
        observaciones: null,
      },
    ],
    alertas: [
      {
        id: 'alert-preview-101',
        medicion_id: 'measure-preview-101',
        nivel_severidad_id: 2,
        nivel_severidad: 'Media',
        tipo_alerta_id: 5,
        tipo_alerta: 'Medición Fuera de Rango',
        mensaje: 'Presión sistólica por encima del rango configurado.',
        atendida: false,
        fecha_alerta: '2026-08-24T15:36:00.000Z',
        fecha_atencion: null,
      },
    ],
  },
};

export const previewMedicalTimeline: Record<number, ClinicalTimelineItem[]> = {
  7001: [
    {
      occurred_at: '2024-04-02T08:00:00.000Z',
      tipo: 'condicion',
      titulo: 'Hipertensión arterial',
      detalle: 'Inicio de condición médica.',
      entidad: 'condiciones_medicas',
      entidad_id: '3201',
    },
    {
      occurred_at: '2026-08-24T15:30:00.000Z',
      tipo: 'consulta',
      titulo: 'Control de presión arterial',
      detalle: 'Paciente estable durante el control.',
      entidad: 'consultas_medicas',
      entidad_id: '3401',
    },
    {
      occurred_at: '2026-08-24T15:35:00.000Z',
      tipo: 'medicion',
      titulo: 'Presión sistólica: 138 mmHg',
      detalle: null,
      entidad: 'mediciones_indicador',
      entidad_id: 'measure-preview-101',
    },
    {
      occurred_at: '2026-08-24T15:40:00.000Z',
      tipo: 'diagnostico',
      titulo: 'Diagnóstico',
      detalle: 'Hipertensión arterial primaria',
      entidad: 'diagnosticos',
      entidad_id: '3301',
    },
    {
      occurred_at: '2026-08-24T15:45:00.000Z',
      tipo: 'receta',
      titulo: 'Receta emitida',
      detalle: 'Control antihipertensivo',
      entidad: 'recetas',
      entidad_id: 'rx-preview-101',
    },
    {
      occurred_at: '2026-08-24T15:46:00.000Z',
      tipo: 'alerta',
      titulo: 'Alerta clínica',
      detalle: 'Presión sistólica por encima del rango configurado.',
      entidad: 'alertas_clinicas',
      entidad_id: 'alert-preview-101',
    },
  ],
};
