"""Add prescriptions and medications models

Revision ID: 0a4546c7327d
Revises: 20260827_08
Create Date: 2026-08-22 17:46:51.679900
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a4546c7327d'
down_revision: Union[str, Sequence[str], None] = '20260827_08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nombre_generico', sa.String(length=150), nullable=True),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('concentracion', sa.String(length=100), nullable=True),
    sa.Column('fabricante', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_nombre'), 'medicamentos', ['nombre'], unique=False)
    op.create_table('recetas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('vigencia_hasta', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas_medicas.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_receta.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales_salud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_consulta_id'), 'recetas', ['consulta_id'], unique=False)
    op.create_index(op.f('ix_recetas_paciente_id'), 'recetas', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_recetas_profesional_id'), 'recetas', ['profesional_id'], unique=False)
    op.create_table('detalles_receta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('receta_id', sa.String(length=36), nullable=False),
    sa.Column('medicamento_id', sa.String(length=36), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('via_administracion_id', sa.Integer(), nullable=False),
    sa.Column('dosis', sa.String(length=50), nullable=False),
    sa.Column('frecuencia', sa.String(length=100), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('cantidad_total', sa.Integer(), nullable=False),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.ForeignKeyConstraint(['via_administracion_id'], ['vias_administracion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_receta_medicamento_id'), 'detalles_receta', ['medicamento_id'], unique=False)
    op.create_index(op.f('ix_detalles_receta_receta_id'), 'detalles_receta', ['receta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_receta_receta_id'), table_name='detalles_receta')
    op.drop_index(op.f('ix_detalles_receta_medicamento_id'), table_name='detalles_receta')
    op.drop_table('detalles_receta')
    op.drop_index(op.f('ix_recetas_profesional_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_paciente_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_consulta_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_medicamentos_nombre'), table_name='medicamentos')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###
