"""Add treatment and communication catalogs

Revision ID: 10c1a979619e
Revises: 20260824_05
Create Date: 2026-08-22 00:47:32.169562
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10c1a979619e'
down_revision: Union[str, Sequence[str], None] = '20260824_05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_dosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_estados_dosis_nombre'), 'estados_dosis', ['nombre'], unique=True)
    op.create_table('estados_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_estados_receta_nombre'), 'estados_receta', ['nombre'], unique=True)
    op.create_table('niveles_severidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_niveles_severidad_nombre'), 'niveles_severidad', ['nombre'], unique=True)
    op.create_table('origenes_registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_origenes_registro_nombre'), 'origenes_registro', ['nombre'], unique=True)
    op.create_table('tipos_alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_alerta_nombre'), 'tipos_alerta', ['nombre'], unique=True)
    op.create_table('tipos_recordatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_recordatorio_nombre'), 'tipos_recordatorio', ['nombre'], unique=True)
    op.create_table('tipos_relacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_relacion_nombre'), 'tipos_relacion', ['nombre'], unique=True)
    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_unidades_medida_nombre'), 'unidades_medida', ['nombre'], unique=True)
    op.create_table('vias_administracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_vias_administracion_nombre'), 'vias_administracion', ['nombre'], unique=True)
    op.drop_constraint(op.f('ck_citas_duracion'), 'citas', type_='check')
    op.drop_constraint(op.f('ck_citas_periodo'), 'citas', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_citas_periodo'), 'citas', 'inicio < fin')
    op.create_check_constraint(op.f('ck_citas_duracion'), 'citas', "fin <= (inicio + '12:00:00'::interval)")
    op.drop_index(op.f('ix_vias_administracion_nombre'), table_name='vias_administracion')
    op.drop_table('vias_administracion')
    op.drop_index(op.f('ix_unidades_medida_nombre'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index(op.f('ix_tipos_relacion_nombre'), table_name='tipos_relacion')
    op.drop_table('tipos_relacion')
    op.drop_index(op.f('ix_tipos_recordatorio_nombre'), table_name='tipos_recordatorio')
    op.drop_table('tipos_recordatorio')
    op.drop_index(op.f('ix_tipos_alerta_nombre'), table_name='tipos_alerta')
    op.drop_table('tipos_alerta')
    op.drop_index(op.f('ix_origenes_registro_nombre'), table_name='origenes_registro')
    op.drop_table('origenes_registro')
    op.drop_index(op.f('ix_niveles_severidad_nombre'), table_name='niveles_severidad')
    op.drop_table('niveles_severidad')
    op.drop_index(op.f('ix_estados_receta_nombre'), table_name='estados_receta')
    op.drop_table('estados_receta')
    op.drop_index(op.f('ix_estados_dosis_nombre'), table_name='estados_dosis')
    op.drop_table('estados_dosis')
    # ### end Alembic commands ###
