"""add_schedules_and_dose_logs_models

Revision ID: 2ee7974d93e3
Revises: 0a4546c7327d
Create Date: 2026-08-22 20:43:37.658526
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ee7974d93e3'
down_revision: Union[str, Sequence[str], None] = '0a4546c7327d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_medicamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detalle_receta_id', sa.String(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detalle_receta_id'], ['detalles_receta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detalle_receta_id', 'hora', name='uq_detalle_hora')
    )
    op.create_table('dosis_administradas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('horario_id', sa.UUID(), nullable=False),
    sa.Column('estado_dosis_id', sa.Integer(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('origen_registro_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado_dosis_id'], ['estados_dosis.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios_medicamento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origen_registro_id'], ['origenes_registro.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dosis_administradas')
    op.drop_table('horarios_medicamento')
    # ### end Alembic commands ###
