"""add health indicators ranges and alerts models

Revision ID: ce75376fbc26
Revises: 2ee7974d93e3
Create Date: 2026-08-22 21:53:28.393696
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce75376fbc26'
down_revision: Union[str, Sequence[str], None] = '2ee7974d93e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicadores_medicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicadores_medicos_codigo'), 'indicadores_medicos', ['codigo'], unique=True)
    op.create_table('rangos_indicador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicador_id', sa.UUID(), nullable=False),
    sa.Column('nivel_severidad_id', sa.Integer(), nullable=False),
    sa.Column('valor_minimo', sa.Float(), nullable=True),
    sa.Column('valor_maximo', sa.Float(), nullable=True),
    sa.Column('etiqueta', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores_medicos.id'], ),
    sa.ForeignKeyConstraint(['nivel_severidad_id'], ['niveles_severidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediciones_indicador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('origen_registro_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('fecha_medicion', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores_medicos.id'], ),
    sa.ForeignKeyConstraint(['origen_registro_id'], ['origenes_registro.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediciones_indicador_paciente_id'), 'mediciones_indicador', ['paciente_id'], unique=False)
    op.create_table('alertas_clinicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medicion_id', sa.UUID(), nullable=False),
    sa.Column('nivel_severidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta_id', sa.Integer(), nullable=False),
    sa.Column('origen_registro_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('atendida', sa.Boolean(), nullable=False),
    sa.Column('atendida_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_alerta', sa.DateTime(), nullable=False),
    sa.Column('fecha_atencion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendida_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['medicion_id'], ['mediciones_indicador.id'], ),
    sa.ForeignKeyConstraint(['nivel_severidad_id'], ['niveles_severidad.id'], ),
    sa.ForeignKeyConstraint(['origen_registro_id'], ['origenes_registro.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tipo_alerta_id'], ['tipos_alerta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_clinicas_paciente_id'), 'alertas_clinicas', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertas_clinicas_paciente_id'), table_name='alertas_clinicas')
    op.drop_table('alertas_clinicas')
    op.drop_index(op.f('ix_mediciones_indicador_paciente_id'), table_name='mediciones_indicador')
    op.drop_table('mediciones_indicador')
    op.drop_table('rangos_indicador')
    op.drop_index(op.f('ix_indicadores_medicos_codigo'), table_name='indicadores_medicos')
    op.drop_table('indicadores_medicos')
    # ### end Alembic commands ###
