"""add reminders notifications preferences and patient relations

Revision ID: da9b16284bf3
Revises: cc0fc6fceb9f
Create Date: 2026-08-23 01:04:55.156119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da9b16284bf3'
down_revision: Union[str, Sequence[str], None] = 'cc0fc6fceb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencias_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('notificar_dosis', sa.Boolean(), nullable=False),
    sa.Column('notificar_citas', sa.Boolean(), nullable=False),
    sa.Column('notificar_alertas', sa.Boolean(), nullable=False),
    sa.Column('permitir_email', sa.Boolean(), nullable=False),
    sa.Column('permitir_push', sa.Boolean(), nullable=False),
    sa.Column('modificado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_preferencias_notificacion_id'), 'preferencias_notificacion', ['id'], unique=False)
    op.create_table('relaciones_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_relacionado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_relacion_id', sa.Integer(), nullable=False),
    sa.Column('recibir_notificaciones', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tipo_relacion_id'], ['tipos_relacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_relacionado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relaciones_paciente_id'), 'relaciones_paciente', ['id'], unique=False)
    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_recordatorio_id', sa.Integer(), nullable=False),
    sa.Column('horario_medicamento_id', sa.UUID(), nullable=True),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('alerta_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas_clinicas.id'], ),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['horario_medicamento_id'], ['horarios_medicamento.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tipo_recordatorio_id'], ['tipos_recordatorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordatorios_id'), 'recordatorios', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('recordatorio_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recordatorio_id'], ['recordatorios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_recordatorios_id'), table_name='recordatorios')
    op.drop_table('recordatorios')
    op.drop_index(op.f('ix_relaciones_paciente_id'), table_name='relaciones_paciente')
    op.drop_table('relaciones_paciente')
    op.drop_index(op.f('ix_preferencias_notificacion_id'), table_name='preferencias_notificacion')
    op.drop_table('preferencias_notificacion')
    # ### end Alembic commands ###
